### PR TITLE
Encrypt only specific arguments or nested properties of arguments

### PR DESCRIPTION
**Pull request by joelvh**
Added fine-grained control over what gets encrypted rather than having the whole payload get encrypted.

### CODE REVIEW

**Comment by wuputah** [comment]
Hi Joel- thanks for sending this pull request! Sorry for not seeing this sooner, I wasn't watching the repository.

Can you explain your use case for this feature? I'm not sure it fits in with what I had intended and would like to understand other use cases.

**Comment by joelvh** [comment]
Hi @wuputah, 

We perform asynchronous processing of credit cards, so we wanted to encrypt the credit card number and related information. We're also peeking into the queues and need to get access to some decrypted parameter values. This is particularly the case when we want to ensure uniqueness with certain jobs, using a Sidekiq plugin that won't queue the same job more than once.

**Comment by joelvh** [comment]
@wuputah just wanted to see if you had a chance to check out my comments.

**Comment by joelvh** [comment]
@wuputah this has been in production for several months and no issues so far. Just rebased to incorporate Sidekiq 3 functionality, as well as backwards-compatibility with Sidekiq 2.5.

**Comment by wuputah** [comment]
Hi Joel- thanks again for your contribution. I'm glad you've been able to continue to maintain this branch easily and hope it continues to do so. However, I honestly don't foresee merging this in, as I'm not comfortable with maintaining the complexity it adds (I'll admit it'd probably be different if I had written it myself!). That said, I would like to support this use case in the future.

FWIW, #3 is somewhat related here, but I;m not sure solving #3 would address your issue if you absolutely need to store data unencrypted for compatibility with other plugins.

**Pull request closed without merging**
